on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - index.html
      - Dockerfile
      - .github/workflows/build-push.yaml

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{secrets.GITHUB_TOKEN }}
      - id: repository
        run: echo "name=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
        shell: bash
      - id: commit-hash
        run: echo "short=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_OUTPUT
        shell: bash
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ steps.repository.outputs.name }}:latest
            ghcr.io/${{ steps.repository.outputs.name }}:${{ steps.commit-hash.outputs.short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - id: image
        run: echo "name=ghcr.io/${{ steps.repository.outputs.name }}:${{ steps.commit-hash.outputs.short }}" >> $GITHUB_OUTPUT
